<?php

namespace Database\Seeders;

use App\Models\CredentialBadge;
use Illuminate\Database\Seeder;

class CompleteCredentialBadgeSeeder extends Seeder
{
    public function run(): void
    {
        CredentialBadge::query()
            ->where('provider', 'credly')
            ->where('external_id', 'credly-profile-brittm')
            ->delete();

        // Public Credly metadata snapshot. Badge verification URLs and mirrored public images are safe to publish.
        $badges = [
            0 => [
                'provider' => 'credly',
                'external_id' => '157eef37-dceb-4c49-a252-3a327601f36c',
                'name' => 'Networking Basics',
                'issuer' => 'Cisco',
                'category' => 'networking',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Networking Basics course and achieved this student level credential. Earner has knowledge of the types of networks, how they work, how devices send and receive data, the types of network cabling, how IP addresses find information on the Internet, how transport and applications operate, and has practiced building a home wireless network. Participated in up to 13 Cisco Packet Tracer activities.',
                'issued_at' => '2026-07-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/157eef37-dceb-4c49-a252-3a327601f36c.png',
                'certificate_url' => 'https://www.credly.com/badges/157eef37-dceb-4c49-a252-3a327601f36c',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Application Layer Services',
                    1 => 'IPv4 Addresses',
                    2 => 'Network Media',
                    3 => 'NetWork Types',
                    4 => 'Protocols Standards',
                    5 => 'Wireless Access',
                ],
                'sort_order' => 0,
                'is_featured' => true,
                'synced_at' => null,
            ],
            1 => [
                'provider' => 'credly',
                'external_id' => '5fb8dbbb-3d12-43dd-ad85-f301b32e63ae',
                'name' => 'SAP Certified - Implementation Consultant - End-to-End Business Processes for SAP Business Suite',
                'issuer' => 'SAP',
                'category' => 'project_management',
                'description' => 'This certification exam verifies that the candidate has the core knowledge about SAP end-to-end business processes and their integration. It is recommended as an entry-level qualification to allow consultants and application users to get acquainted with SAP end-to-end business process fundamentals.',
                'issued_at' => '2026-06-02',
                'expires_at' => '2027-06-03',
                'image_url' => '/imports/credly/5fb8dbbb-3d12-43dd-ad85-f301b32e63ae.png',
                'certificate_url' => 'https://www.credly.com/badges/5fb8dbbb-3d12-43dd-ad85-f301b32e63ae',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Financial Accounting',
                    1 => 'Management Accounting',
                    2 => 'Manufacturing Processes',
                    3 => 'Purchasing',
                    4 => 'Sales Process',
                    5 => 'SAP Cloud Suite Portfolio',
                ],
                'sort_order' => 1,
                'is_featured' => true,
                'synced_at' => null,
            ],
            2 => [
                'provider' => 'credly',
                'external_id' => '860f8dd9-aafb-44c0-9331-8a935df96a54',
                'name' => 'English for IT: Advice and Time',
                'issuer' => 'Cisco',
                'category' => 'networking',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies the earner of this badge successfully completed the “English for IT: Advice and Time” course. Earners demonstrate accurate use of modal verbs to give advice, make suggestions, express obligation, and discuss past possibilities in IT contexts. They effectively apply present continuous and present perfect tenses to describe ongoing and past actions and use conditionals and imperatives to communicate instructions and outcomes in IT scenarios.',
                'issued_at' => '2026-05-04',
                'expires_at' => null,
                'image_url' => '/imports/credly/860f8dd9-aafb-44c0-9331-8a935df96a54.png',
                'certificate_url' => 'https://www.credly.com/badges/860f8dd9-aafb-44c0-9331-8a935df96a54',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Conditional Sentences',
                    1 => 'Imperative Forms',
                    2 => 'Modal Verbs',
                    3 => 'Present Continuous',
                    4 => 'Present Perfect',
                ],
                'sort_order' => 2,
                'is_featured' => true,
                'synced_at' => null,
            ],
            3 => [
                'provider' => 'credly',
                'external_id' => '32cdedc3-fb04-422b-8806-1e2fb7076d23',
                'name' => 'English for IT: Describing and Comparing',
                'issuer' => 'Cisco',
                'category' => 'project_management',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies the earner of this badge successfully completed the "English for IT: Describing and Comparing” course. Earners demonstrate accurate use of determiners, articles, idioms, phrasal verbs, and comparative forms in IT contexts. They understand vocabulary related to teamwork, project management, and data analysis, and can describe and compare processes, challenges, and collaboration in digital projects effectively.',
                'issued_at' => '2026-05-04',
                'expires_at' => null,
                'image_url' => '/imports/credly/32cdedc3-fb04-422b-8806-1e2fb7076d23.png',
                'certificate_url' => 'https://www.credly.com/badges/32cdedc3-fb04-422b-8806-1e2fb7076d23',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Adverbs',
                    1 => 'Articles',
                    2 => 'Comparative Forms',
                    3 => 'Countable and Uncountable Nouns',
                    4 => 'Idioms',
                    5 => 'Phrasal Verbs',
                    6 => 'Prepositions',
                    7 => 'Superlative Forms',
                ],
                'sort_order' => 3,
                'is_featured' => false,
                'synced_at' => null,
            ],
            4 => [
                'provider' => 'credly',
                'external_id' => 'd78c3e54-a111-4b37-b7cb-2ecdbf7b775e',
                'name' => 'English for IT: Needs and Responsibilities',
                'issuer' => 'Cisco',
                'category' => 'networking',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies the earner of this badge successfully completed the “English for IT: Needs and Responsibilities” course. Earners demonstrate proficiency in using transitive verbs and passive voice to describe IT actions and processes. They accurately apply software development vocabulary, modal verbs for necessity and obligation, and use relative clauses, gerunds, and to-infinitive phrases to communicate responsibilities, collaboration, and plans in IT contexts.',
                'issued_at' => '2026-05-03',
                'expires_at' => null,
                'image_url' => '/imports/credly/d78c3e54-a111-4b37-b7cb-2ecdbf7b775e.png',
                'certificate_url' => 'https://www.credly.com/badges/d78c3e54-a111-4b37-b7cb-2ecdbf7b775e',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Adjectives',
                    1 => 'Gerunds',
                    2 => 'Modals of Obligation',
                    3 => 'Modal Verbs',
                    4 => 'Relative Clauses',
                    5 => 'Transitive Verbs',
                ],
                'sort_order' => 4,
                'is_featured' => false,
                'synced_at' => null,
            ],
            5 => [
                'provider' => 'credly',
                'external_id' => 'c93e5813-1e7d-44b8-8975-48a773c91ece',
                'name' => 'English for IT: People and Quantities',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies the earner of this badge successfully completed the “English for IT: People and Quantities” course. Earners demonstrate proficiency in using generic, impersonal, and indefinite compound pronouns, as well as quantifiers to communicate clearly in IT contexts. They understand key cybersecurity vocabulary, apply polite indirect questions, and use adjective formation to describe workplace qualities and project performance accurately.',
                'issued_at' => '2026-05-03',
                'expires_at' => null,
                'image_url' => '/imports/credly/c93e5813-1e7d-44b8-8975-48a773c91ece.png',
                'certificate_url' => 'https://www.credly.com/badges/c93e5813-1e7d-44b8-8975-48a773c91ece',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Adjective Formation with Prefixes and Suffixes',
                    1 => 'Cybersecurity Vocabulary',
                    2 => 'Determiners',
                    3 => 'Generic and Impersonal Pronouns',
                    4 => 'Indefinite Compound Pronouns',
                    5 => 'Polite Indirect Questions',
                    6 => 'Quantifiers',
                ],
                'sort_order' => 5,
                'is_featured' => false,
                'synced_at' => null,
            ],
            6 => [
                'provider' => 'credly',
                'external_id' => 'b7a5bc6b-49ce-45f3-905c-5b9aeab00fd4',
                'name' => 'IT Customer Support Basics',
                'issuer' => 'Cisco',
                'category' => 'networking',
                'description' => 'Cisco verifies the earner of this badge successfully completed the IT Customer Support Basics course. This student-level credential demonstrates foundational knowledge in help desk operations, customer service, and remote troubleshooting. The holder is proficient in using industry-standard tools to assist users in resolving technical issues and can effectively communicate technical concepts to non-technical users.',
                'issued_at' => '2026-04-07',
                'expires_at' => null,
                'image_url' => '/imports/credly/b7a5bc6b-49ce-45f3-905c-5b9aeab00fd4.png',
                'certificate_url' => 'https://www.credly.com/badges/b7a5bc6b-49ce-45f3-905c-5b9aeab00fd4',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Customer Service',
                    1 => 'Documentation and Reporting',
                    2 => 'Effective Communication',
                    3 => 'Help Desk Concepts',
                    4 => 'Remote Troubleshooting',
                    5 => 'Technical Problem Solving',
                ],
                'sort_order' => 6,
                'is_featured' => false,
                'synced_at' => null,
            ],
            7 => [
                'provider' => 'credly',
                'external_id' => 'f0304e9a-ef78-4bd7-b876-7690e65864f1',
                'name' => 'Google Business Intelligence Professional Certificate(v.2)',
                'issuer' => 'Coursera',
                'category' => 'ai_data',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The course objective is to build on data analytics skills and experience to take one\'s career to the next level. It is designed for graduates of the Google Data Analytics Certificate or people with equivalent data analytics experience.',
                'issued_at' => '2026-01-15',
                'expires_at' => null,
                'image_url' => '/imports/credly/f0304e9a-ef78-4bd7-b876-7690e65864f1.png',
                'certificate_url' => 'https://www.credly.com/badges/f0304e9a-ef78-4bd7-b876-7690e65864f1',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Career Development',
                    1 => 'Data Modeling',
                    2 => 'Decision Making',
                    3 => 'Foundations Of Business Intelligence',
                ],
                'sort_order' => 7,
                'is_featured' => false,
                'synced_at' => null,
            ],
            8 => [
                'provider' => 'credly',
                'external_id' => '6f523250-7c29-46b4-a390-9aea86e0b6c9',
                'name' => 'Google Digital Marketing & E-commerce Professional Certificate(v.2)',
                'issuer' => 'Coursera',
                'category' => 'ai_data',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The certificate objective is to cover key areas such as search and email marketing, social media, analytics, and building online stores through hands-on projects and tools like Google Ads, Google Analytics, and Shopify. This is a beginner-friendly online program that prepares learners for entry-level roles in digital marketing and e-commerce.',
                'issued_at' => '2026-01-15',
                'expires_at' => null,
                'image_url' => '/imports/credly/6f523250-7c29-46b4-a390-9aea86e0b6c9.png',
                'certificate_url' => 'https://www.credly.com/badges/6f523250-7c29-46b4-a390-9aea86e0b6c9',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Career Development',
                    1 => 'E-Commerce',
                    2 => 'Introduction To Digital Marketing',
                    3 => 'Search Marketing',
                ],
                'sort_order' => 8,
                'is_featured' => false,
                'synced_at' => null,
            ],
            9 => [
                'provider' => 'credly',
                'external_id' => '3b2c2825-d5d9-4721-abf5-b6e8e30aa75e',
                'name' => 'Google IT Automation with Python Professional Certificate(v.1)',
                'issuer' => 'Coursera',
                'category' => 'project_management',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The certificate objective is to cover Python programming, Git and GitHub, IT automation, configuration management, and cloud computing through hands-on labs and real-world projects. This is an advanced, online program designed for learners with prior IT experience who want to expand their skills into automation and scripting.',
                'issued_at' => '2026-01-16',
                'expires_at' => null,
                'image_url' => '/imports/credly/3b2c2825-d5d9-4721-abf5-b6e8e30aa75e.png',
                'certificate_url' => 'https://www.credly.com/badges/3b2c2825-d5d9-4721-abf5-b6e8e30aa75e',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Cloud Technologies',
                    1 => 'Introduction To Computer Programming',
                    2 => 'Introduction To Operating Systems',
                    3 => 'Introduction To Python Programming',
                    4 => 'Software Development Using Python',
                ],
                'sort_order' => 9,
                'is_featured' => false,
                'synced_at' => null,
            ],
            10 => [
                'provider' => 'credly',
                'external_id' => 'd5ce76a3-9520-4f5e-a027-f6d5dbe473ca',
                'name' => 'Google UX Design Professional Certificate(v.3)',
                'issuer' => 'Coursera',
                'category' => 'design_marketing',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The course objective is to prepare learners for a career in the high-growth field of UX design with professional training designed by Google and hosted on Coursera. Students will gain in demand skills preparing them for an entry-level job.',
                'issued_at' => '2026-01-14',
                'expires_at' => null,
                'image_url' => '/imports/credly/d5ce76a3-9520-4f5e-a027-f6d5dbe473ca.png',
                'certificate_url' => 'https://www.credly.com/badges/d5ce76a3-9520-4f5e-a027-f6d5dbe473ca',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Advanced User Experience (UX) Design',
                    1 => 'Career Development',
                    2 => 'Career Development In UX Design',
                    3 => 'Introduction To Web Design',
                    4 => 'Principles Of User Experience (UX) Design',
                ],
                'sort_order' => 10,
                'is_featured' => false,
                'synced_at' => null,
            ],
            11 => [
                'provider' => 'credly',
                'external_id' => '035d5b26-5deb-420c-96a7-4919ea2f9654',
                'name' => 'Google Advanced Data Analytics Professional Certificate(v.2)',
                'issuer' => 'Coursera',
                'category' => 'project_management',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The course objective is to build on data analytics skills and experience to take one\'s career to the next level. It is designed for graduates of the Google Data Analytics Certificate or people with equivalent data analytics experience.',
                'issued_at' => '2026-01-13',
                'expires_at' => null,
                'image_url' => '/imports/credly/035d5b26-5deb-420c-96a7-4919ea2f9654.png',
                'certificate_url' => 'https://www.credly.com/badges/035d5b26-5deb-420c-96a7-4919ea2f9654',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Advanced Analytics',
                    1 => 'Applied Machine Learning',
                    2 => 'Data Cleansing',
                    3 => 'Data-Driven Decision-Making',
                    4 => 'Data Structures',
                    5 => 'Decision Tree Learning',
                    6 => 'Descriptive Statistics',
                    7 => 'Interactive Data Visualization',
                    8 => 'Interviewing Skills',
                    9 => 'Logistic Regression',
                    10 => 'NumPy',
                    11 => 'Probability Distribution',
                    12 => 'Probability & Statistics',
                    13 => 'Professional Development',
                    14 => 'Statistical Inference',
                    15 => 'Statistical Methods',
                    16 => 'Statistical Modeling',
                    17 => 'Statistics',
                    18 => 'Supervised Learning',
                    19 => 'Workflow Management',
                ],
                'sort_order' => 11,
                'is_featured' => false,
                'synced_at' => null,
            ],
            12 => [
                'provider' => 'credly',
                'external_id' => '39e86190-5c5c-4e38-aad5-3703bb8fd269',
                'name' => 'Google Project Management Professional Certificate(v.3)',
                'issuer' => 'Coursera',
                'category' => 'project_management',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The course objective is to prepare learners for a career in the in-demand field of project management with professional training designed by Google and hosted on Coursera. Students will gain in-demand skills preparing them for an entry-level job.',
                'issued_at' => '2026-01-12',
                'expires_at' => null,
                'image_url' => '/imports/credly/39e86190-5c5c-4e38-aad5-3703bb8fd269.png',
                'certificate_url' => 'https://www.credly.com/badges/39e86190-5c5c-4e38-aad5-3703bb8fd269',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Agile Project Management',
                    1 => 'Career Development',
                    2 => 'Introduction To Project Management',
                    3 => 'Project Management',
                ],
                'sort_order' => 12,
                'is_featured' => false,
                'synced_at' => null,
            ],
            13 => [
                'provider' => 'credly',
                'external_id' => '0a4e2f25-49b8-4108-8f9e-d4f1bbdd3e5c',
                'name' => 'Google IT Support Professional Certificate(v.3)',
                'issuer' => 'Coursera',
                'category' => 'cybersecurity',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The certificate objective is to cover computer hardware and software, networking, system administration, security, and troubleshooting through hands-on labs and interactive content. No prior experience is required, and graduates gain job-ready skills recognized by employers. This is a beginner-friendly, online program designed to prepare learners for entry-level roles in IT support.',
                'issued_at' => '2026-01-08',
                'expires_at' => null,
                'image_url' => '/imports/credly/0a4e2f25-49b8-4108-8f9e-d4f1bbdd3e5c.png',
                'certificate_url' => 'https://www.credly.com/badges/0a4e2f25-49b8-4108-8f9e-d4f1bbdd3e5c',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Introduction To Computers',
                    1 => 'Introduction To Cybersecurity',
                    2 => 'Networking Fundamentals',
                    3 => 'Operating Systems',
                    4 => 'Systems Administration',
                ],
                'sort_order' => 13,
                'is_featured' => false,
                'synced_at' => null,
            ],
            14 => [
                'provider' => 'credly',
                'external_id' => '912b3885-5869-448c-a19a-313dd024b5c8',
                'name' => 'Google Cybersecurity Professional Certificate(v.2)',
                'issuer' => 'Coursera',
                'category' => 'cybersecurity',
                'description' => 'This course is offered through Coursera, which is an ACE Authorized Instructional Platform. The course objective is to learn from cybersecurity experts at Google and gain in-demand skills that prepare learners for entry-level roles like cybersecurity analyst, security operations center (SOC) analyst, and more.',
                'issued_at' => '2026-01-07',
                'expires_at' => null,
                'image_url' => '/imports/credly/912b3885-5869-448c-a19a-313dd024b5c8.png',
                'certificate_url' => 'https://www.credly.com/badges/912b3885-5869-448c-a19a-313dd024b5c8',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Attacks',
                    1 => 'Career Development',
                    2 => 'Exploits',
                    3 => 'Introduction To Linux',
                    4 => 'Security Fundamentals',
                ],
                'sort_order' => 14,
                'is_featured' => false,
                'synced_at' => null,
            ],
            15 => [
                'provider' => 'credly',
                'external_id' => '867a5686-393e-432c-b197-5fa52a7a14a6',
                'name' => 'Hardware and Upgrade Support',
                'issuer' => 'Cisco',
                'category' => 'networking',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Hardware and Upgrade Support course. This course builds foundational knowledge for working safely with computer hardware. Learners practice safety procedures, identify ports and cables, assist users with device info, and troubleshoot common hardware issues. They also gain hands-on experience installing and upgrading components to support maintenance and perform essential computer repairs.',
                'issued_at' => '2025-09-30',
                'expires_at' => null,
                'image_url' => '/imports/credly/867a5686-393e-432c-b197-5fa52a7a14a6.png',
                'certificate_url' => 'https://www.credly.com/badges/867a5686-393e-432c-b197-5fa52a7a14a6',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Component Installation',
                    1 => 'Failure Analysis',
                    2 => 'Hardware Identification',
                    3 => 'Hardware Troubleshooting',
                    4 => 'Safety Practices',
                    5 => 'System Information Guidance',
                    6 => 'Upgrade Assessment',
                ],
                'sort_order' => 15,
                'is_featured' => false,
                'synced_at' => null,
            ],
            16 => [
                'provider' => 'credly',
                'external_id' => '95c6d142-23bf-45bd-b3b2-3ba906721648',
                'name' => 'Apply AI: Analyze Customer Reviews',
                'issuer' => 'Cisco',
                'category' => 'networking',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Apply AI: Analyze Customer Reviews Course. The learner has applied thematic analysis to analyze tables of text data with assistance of AI and spreadsheet apps. The learner has practiced choosing the right AI or non-AI tool for each task.',
                'issued_at' => '2025-09-03',
                'expires_at' => null,
                'image_url' => '/imports/credly/95c6d142-23bf-45bd-b3b2-3ba906721648.png',
                'certificate_url' => 'https://www.credly.com/badges/95c6d142-23bf-45bd-b3b2-3ba906721648',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'AI Tool Selection',
                    1 => 'LLM Prompting',
                    2 => 'Spreadsheet Formulas',
                    3 => 'Tabular Data',
                    4 => 'Thematic Analysis',
                ],
                'sort_order' => 16,
                'is_featured' => false,
                'synced_at' => null,
            ],
            17 => [
                'provider' => 'credly',
                'external_id' => 'f1b9f3a3-8b49-414b-96a6-d0ff3727d523',
                'name' => 'Create Digital Content, Communicate and Collaborate Online',
                'issuer' => 'Cisco',
                'category' => 'project_management',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies that the learner has demonstrated the ability to create digital content, effectively communicate, and collaborate online. Through this entry-level course, the learner has acquired essential skills to start creating digital content, communicate effectively using digital tools, and collaborate efficiently in personal, remote and hybrid working environments.',
                'issued_at' => '2025-09-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/f1b9f3a3-8b49-414b-96a6-d0ff3727d523.png',
                'certificate_url' => 'https://www.credly.com/badges/f1b9f3a3-8b49-414b-96a6-d0ff3727d523',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Digital Accessibility',
                    1 => 'Digital Collaboration',
                    2 => 'Digital Communication',
                    3 => 'Digital Document Creation',
                    4 => 'Digital Etiquette',
                    5 => 'File Management and Backup',
                    6 => 'Hybrid Working Tools',
                    7 => 'Remote Work Skills',
                ],
                'sort_order' => 17,
                'is_featured' => false,
                'synced_at' => null,
            ],
            18 => [
                'provider' => 'credly',
                'external_id' => '6ff82ae2-512a-4c48-92fb-f7c9b4ff8200',
                'name' => 'Endpoint Security',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Endpoint Security course. The holder of this student-level credential has a broad understanding of basic concepts of network security, as well as operating systems and endpoint security.',
                'issued_at' => '2025-07-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/6ff82ae2-512a-4c48-92fb-f7c9b4ff8200.png',
                'certificate_url' => 'https://www.credly.com/badges/6ff82ae2-512a-4c48-92fb-f7c9b4ff8200',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Antimalware Protection',
                    1 => 'Application Security',
                    2 => 'Common Cyber Threats',
                    3 => 'Defending Systems And Devices',
                    4 => 'Host-based Intrusion Prevention',
                    5 => 'IP/TCP/UDP Vulnerabilities',
                    6 => 'Linux Basics',
                    7 => 'Mitigating Common Network Attacks',
                    8 => 'Network Security Infrastructure',
                    9 => 'Securing WLANs',
                    10 => 'System And Endpoint Protection',
                    11 => 'Windows Security',
                    12 => 'Wireless And Mobile Device Attacks',
                ],
                'sort_order' => 18,
                'is_featured' => false,
                'synced_at' => null,
            ],
            19 => [
                'provider' => 'credly',
                'external_id' => 'eb5ec1be-025c-459a-9432-b230f65ac582',
                'name' => 'English for IT 1',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies the earner of this badge successfully completed the English for IT 1 course and achieved the student level credentials. Earners know how to use complex grammatical concepts correctly; they are familiar with concepts related to information security and job roles, and are able to understand phrases related to customer support; they can use vocabulary related to user experience, fraudulent calls, and network and software engineering.',
                'issued_at' => '2025-02-03',
                'expires_at' => null,
                'image_url' => '/imports/credly/eb5ec1be-025c-459a-9432-b230f65ac582.png',
                'certificate_url' => 'https://www.credly.com/badges/eb5ec1be-025c-459a-9432-b230f65ac582',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Adverbs',
                    1 => 'Compilers and Interpreters Vocabulary',
                    2 => 'Fraudulent Calls Vocabulary',
                    3 => 'Future Perfect',
                    4 => 'Idiomatic Phrases',
                    5 => 'Imperative Instruction',
                    6 => 'Information Security Policy',
                    7 => 'Inversion',
                    8 => 'Job Roles and Responsibilities',
                    9 => 'Modal Verbs',
                    10 => 'Network and Software Engineering Vocabulary',
                    11 => 'Passive Voice',
                    12 => 'Past Simple',
                    13 => 'Relative Pronouns',
                    14 => 'Supplier Evaluation Modules',
                    15 => 'User Experience Vocabulary',
                ],
                'sort_order' => 19,
                'is_featured' => false,
                'synced_at' => null,
            ],
            20 => [
                'provider' => 'credly',
                'external_id' => 'd70f20c5-51bf-49a8-a3f7-dc3a3ebdf49c',
                'name' => 'English for IT 2',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco, in collaboration with OpenEDG, verifies the earner of this badge successfully completed the English for IT 2 course and achieved the student level credentials. Earners know how to use grammar related to mood, sentence structure and conjunctions; they have an upper-intermediate knowledge of tenses; they can make logical deductions and polite requests, use key phrases related to networking, customer support, software and security engineering, and communicate in English at CEFR B2 level.',
                'issued_at' => '2025-02-03',
                'expires_at' => null,
                'image_url' => '/imports/credly/d70f20c5-51bf-49a8-a3f7-dc3a3ebdf49c.png',
                'certificate_url' => 'https://www.credly.com/badges/d70f20c5-51bf-49a8-a3f7-dc3a3ebdf49c',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Advanced Modal Verbs',
                    1 => 'Advanced Tenses',
                    2 => 'Cleft Sentences',
                    3 => 'Cloud Computing Vocabulary',
                    4 => 'Conjunctions',
                    5 => 'Customer Support Vocabulary',
                    6 => 'Logical Deductions',
                    7 => 'Networking Vocabulary',
                    8 => 'Polite Requests',
                    9 => 'Sharing Feedback Vocabulary',
                    10 => 'Software Vocabulary',
                    11 => 'Subjunctive Mood',
                    12 => '"They" as singular',
                    13 => 'Updating Colleagues Vocabulary',
                ],
                'sort_order' => 20,
                'is_featured' => false,
                'synced_at' => null,
            ],
            21 => [
                'provider' => 'credly',
                'external_id' => 'dab833b1-aa74-42ed-abe7-9e1f258ce39c',
                'name' => 'Cyber Threat Management',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Cyber Threat Management course. The holder of this student-level credential is familiar with cybersecurity policies and governance to ensure an organization complies with ethics standards and legal and regulatory frameworks. They understand how to do a network vulnerability assessment and create a risk management plan, as well as post-incident response.',
                'issued_at' => '2025-02-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/dab833b1-aa74-42ed-abe7-9e1f258ce39c.png',
                'certificate_url' => 'https://www.credly.com/badges/dab833b1-aa74-42ed-abe7-9e1f258ce39c',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Common Vulnerability Scoring System (CVSS)',
                    1 => 'Disaster Recovery',
                    2 => 'Evidence Handling And Attack Attribution',
                    3 => 'Governance',
                    4 => 'Incident Response',
                    5 => 'Network And Server Profiling',
                    6 => 'Penetration Testing',
                    7 => 'Risk Assessment',
                    8 => 'Risk Management',
                    9 => 'Secure Device Management',
                    10 => 'Security Assessments',
                    11 => 'Security Controls',
                    12 => 'The Cyber Kill Chain',
                    13 => 'The Diamond Model Of Intrusion Analysis',
                    14 => 'Threat Intelligence Services',
                ],
                'sort_order' => 21,
                'is_featured' => false,
                'synced_at' => null,
            ],
            22 => [
                'provider' => 'credly',
                'external_id' => '959d121e-9e8b-4569-bbcd-cf214247c433',
                'name' => 'Ethical Hacker',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Ethical Hacker course. The holder of this student level credential has a broad understanding of the legal and compliance requirements and is proficient in the art of scoping, executing, reporting vulnerability assessments, and recommending mitigation strategies. The holder has completed up to 34 hands-on activities using Kali Linux, WebSploit, and other tools.',
                'issued_at' => '2025-02-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/959d121e-9e8b-4569-bbcd-cf214247c433.png',
                'certificate_url' => 'https://www.credly.com/badges/959d121e-9e8b-4569-bbcd-cf214247c433',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Ethical Hacking',
                    1 => 'Exploiting Applications',
                    2 => 'Exploiting Networks',
                    3 => 'IoT Security',
                    4 => 'Penetration Testing',
                    5 => 'Pentesting Tools',
                    6 => 'Reporting',
                    7 => 'Social Engineering',
                    8 => 'Vulnerability Assessment',
                    9 => 'Vulnerability Scanning',
                ],
                'sort_order' => 22,
                'is_featured' => false,
                'synced_at' => null,
            ],
            23 => [
                'provider' => 'credly',
                'external_id' => '898629e9-a92d-40d1-8c87-1b8217949048',
                'name' => 'Introduction to Modern AI',
                'issuer' => 'Cisco',
                'category' => 'ai_data',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Introduction to Modern AI course. The learner will have practiced using AI enabled features on free apps, such as photo apps, translation services, and chatbots. They will have had in depth practice in prompting a chatbot, and understand fundamentals of how the models work, which informs how they prompt chatbots.',
                'issued_at' => '2025-02-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/898629e9-a92d-40d1-8c87-1b8217949048.png',
                'certificate_url' => 'https://www.credly.com/badges/898629e9-a92d-40d1-8c87-1b8217949048',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'AI Learning',
                    1 => 'Chatbots',
                    2 => 'Computer Vision',
                    3 => 'Machine Learning',
                    4 => 'Machine Translation',
                    5 => 'Prompting Tips',
                ],
                'sort_order' => 23,
                'is_featured' => false,
                'synced_at' => null,
            ],
            24 => [
                'provider' => 'credly',
                'external_id' => 'af8c29cf-3b93-49f3-ac9d-61c398bf1650',
                'name' => 'Network Defense',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Network Defense course. The holder of this student-level credential has a broad understanding of techniques to monitor and protect the network, including access control, firewalls, cloud security, and cryptography. They are also familiar with how to evaluate and respond to security alerts.',
                'issued_at' => '2025-02-02',
                'expires_at' => null,
                'image_url' => '/imports/credly/af8c29cf-3b93-49f3-ac9d-61c398bf1650.png',
                'certificate_url' => 'https://www.credly.com/badges/af8c29cf-3b93-49f3-ac9d-61c398bf1650',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Access Controls',
                    1 => 'Application Security',
                    2 => 'Cloud Security',
                    3 => 'Defense-in-Depth',
                    4 => 'End Device Logs',
                    5 => 'Evaluating Alerts',
                    6 => 'Firewalls',
                    7 => 'Hashing',
                    8 => 'Integrity And Authenticity',
                    9 => 'Network Hardening',
                    10 => 'Network Logs',
                    11 => 'Physical Security',
                    12 => 'Public Key Cryptography',
                    13 => 'Security Policies - Regulations - Standards',
                    14 => 'System And Network Defense',
                ],
                'sort_order' => 24,
                'is_featured' => false,
                'synced_at' => null,
            ],
            25 => [
                'provider' => 'credly',
                'external_id' => '5e747efd-1bb6-41d3-9fd5-ba4d1bf11a3b',
                'name' => 'Google Data Analytics Professional Certificate',
                'issuer' => 'Coursera',
                'category' => 'ai_data',
                'description' => 'Those who earn the Google Data Analytics Certificate, developed by Google, have demonstrated their competence in foundational data analysis. Through hands-on activities and assessments, graduates develop proficiency in preparing, processing, analyzing, and sharing data using tools and platforms including spreadsheets, SQL, Tableau, and R, preparing them for introductory-level roles in data analytics.',
                'issued_at' => '2024-07-11',
                'expires_at' => null,
                'image_url' => '/imports/credly/5e747efd-1bb6-41d3-9fd5-ba4d1bf11a3b.png',
                'certificate_url' => 'https://www.credly.com/badges/5e747efd-1bb6-41d3-9fd5-ba4d1bf11a3b',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Data Aggregation',
                    1 => 'Data Analytics',
                    2 => 'Data Calculations',
                    3 => 'Data Cleaning',
                    4 => 'Data Ethics',
                    5 => 'Data Visualization',
                    6 => 'Presentations',
                    7 => 'Problem Solving',
                    8 => 'R',
                    9 => 'Spreadsheets',
                    10 => 'SQL',
                    11 => 'Structured Thinking',
                ],
                'sort_order' => 25,
                'is_featured' => false,
                'synced_at' => null,
            ],
            26 => [
                'provider' => 'credly',
                'external_id' => '8e60a6b0-36bd-4158-a009-73944e107458',
                'name' => 'Introduction to IoT',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Introduction to Internet of Things course. The holder of this student-level credential has introductory knowledge of IoT and has an understanding how it enables the Digital Transformation along with emerging technologies such as data analytics, AI/ML and the increased attention on cybersecurity. They understand the importance of Intent Based Networking to be able to connect and secure tens of billions of new devices with ease.',
                'issued_at' => '2024-07-10',
                'expires_at' => null,
                'image_url' => '/imports/credly/8e60a6b0-36bd-4158-a009-73944e107458.png',
                'certificate_url' => 'https://www.credly.com/badges/8e60a6b0-36bd-4158-a009-73944e107458',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Digital Transformation',
                    1 => 'Internet Of Things',
                    2 => 'IoT',
                ],
                'sort_order' => 26,
                'is_featured' => false,
                'synced_at' => null,
            ],
            27 => [
                'provider' => 'credly',
                'external_id' => '4bcea0d2-a50f-45c5-afea-7ecaf4fc46f7',
                'name' => 'Introduction to Cybersecurity',
                'issuer' => 'Cisco',
                'category' => 'cybersecurity',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Introduction to Cybersecurity course. The holder of this student-level credential has introductory knowledge of cybersecurity, including the global implications of cyber threats on industries, and why cybersecurity is a growing profession. They understand vulnerabilities and threat detection and defense. They also have insight into opportunities available with pursuing cybersecurity certifications.',
                'issued_at' => '2024-07-10',
                'expires_at' => null,
                'image_url' => '/imports/credly/4bcea0d2-a50f-45c5-afea-7ecaf4fc46f7.png',
                'certificate_url' => 'https://www.credly.com/badges/4bcea0d2-a50f-45c5-afea-7ecaf4fc46f7',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Cyber Best Practices',
                    1 => 'Cybersecurity',
                    2 => 'Network Vulnerabilities',
                    3 => 'Privacy And Data Confidentiality',
                    4 => 'Threat Detection',
                ],
                'sort_order' => 27,
                'is_featured' => false,
                'synced_at' => null,
            ],
            28 => [
                'provider' => 'credly',
                'external_id' => 'cae5f06c-e0ce-4774-a4c2-538065053498',
                'name' => 'Introduction to Data Science',
                'issuer' => 'Cisco',
                'category' => 'ai_data',
                'description' => 'Cisco verifies the earner of this badge successfully completed the Introduction to Data Science course. The holder of this student-level credential has a broad understanding in basic concepts of Data Analytics, Data Engineering, Data Science and AI/ML related job functions. They also have insight into opportunities available for pursuing career in various data roles.',
                'issued_at' => '2024-07-10',
                'expires_at' => null,
                'image_url' => '/imports/credly/cae5f06c-e0ce-4774-a4c2-538065053498.png',
                'certificate_url' => 'https://www.credly.com/badges/cae5f06c-e0ce-4774-a4c2-538065053498',
                'criteria_url' => null,
                'evidence_url' => null,
                'skills' => [
                    0 => 'Data Analysis',
                    1 => 'Data Collection',
                    2 => 'Data Validation',
                ],
                'sort_order' => 28,
                'is_featured' => false,
                'synced_at' => null,
            ],
        ];

        foreach ($badges as $badge) {
            CredentialBadge::query()->updateOrCreate(
                [
                    'provider' => $badge['provider'],
                    'external_id' => $badge['external_id'],
                ],
                $badge,
            );
        }
    }
}
