<?php

return [
    [
        'key' => 'digital-transformation-consulting',
        'number' => '01',
        'title' => 'Digital Transformation & IT Consulting',
        'summary' => 'Independent guidance that turns operational problems into a practical systems roadmap before time and resources are committed to the wrong solution.',
        'best_for' => 'Public-service, education, health, and growing teams that need clarity on processes, requirements, platforms, governance, or implementation priorities.',
        'deliverables' => [
            'Discovery and stakeholder sessions',
            'Current-state process and risk map',
            'Requirements and options assessment',
            'Prioritized implementation roadmap',
        ],
        'tools' => ['Systems analysis', 'Agile', 'Lean Six Sigma', 'SAP', 'Google Workspace', 'Notion'],
        'timeline' => 'By scope',
        'proof_label' => 'View systems background',
        'proof_url' => '/#background',
    ],
    [
        'key' => 'web-systems',
        'number' => '02',
        'title' => 'Custom Web & Information Systems',
        'summary' => 'Purpose-built public websites, internal systems, and admin workspaces that turn real operational requirements into maintainable digital services.',
        'best_for' => 'Institutions, researchers, and small organizations replacing fragmented, manual, or spreadsheet-heavy workflows.',
        'deliverables' => [
            'Discovery and requirements map',
            'Responsive public and admin interfaces',
            'Database, roles, and workflow implementation',
            'Deployment, documentation, and handover',
        ],
        'tools' => ['Laravel', 'PHP', 'Vue.js', 'Inertia.js', 'SQL', 'cPanel'],
        'timeline' => 'Project-based',
        'proof_label' => 'See systems work',
        'proof_url' => '/#work',
    ],
    [
        'key' => 'data-analytics',
        'number' => '03',
        'title' => 'Data Analytics, Dashboards & Decision Support',
        'summary' => 'Decision-ready dashboards, reporting workflows, forecasting, and research analysis that make complex operational or health data easier to act on.',
        'best_for' => 'Programs and teams that need cleaner reporting, useful KPIs, forecasting support, or a stronger evidence base for decisions.',
        'deliverables' => [
            'Data audit, cleaning, and metric design',
            'Interactive dashboard or analytical workflow',
            'Forecasting and risk-analysis support',
            'Findings, methods note, and team walkthrough',
        ],
        'tools' => ['Power BI', 'Excel', 'SQL', 'Python', 'BigQuery', 'FHSIS'],
        'timeline' => 'Project-based',
        'proof_label' => 'See dashboards & research',
        'proof_url' => '/#work',
    ],
    [
        'key' => 'health-information-systems',
        'number' => '04',
        'title' => 'Health Information Systems & EMR Enablement',
        'summary' => 'Readiness, implementation, training, monitoring, and reporting support informed by direct health-facility and Department of Health experience.',
        'best_for' => 'Health offices, facilities, and program teams preparing to implement, strengthen, or evaluate digital health and reporting workflows.',
        'deliverables' => [
            'Readiness and workflow assessment',
            'Implementation and data-validation plan',
            'User training and practical job aids',
            'Monitoring and technical support plan',
        ],
        'tools' => ['EMR', 'FHSIS', 'Health informatics', 'Data privacy', 'Power BI', 'Excel'],
        'timeline' => 'By facility or program',
        'proof_label' => 'See health systems experience',
        'proof_url' => '/#background',
    ],
    [
        'key' => 'ai-automation',
        'number' => '05',
        'title' => 'AI, Automation & Responsible AI Enablement',
        'summary' => 'Human-reviewed automations and AI-assisted workflows that reduce repetitive information work while keeping sources, responsibility, and controls visible.',
        'best_for' => 'Teams exploring practical automation, source-grounded knowledge workflows, or responsible AI adoption without losing human oversight.',
        'deliverables' => [
            'Workflow and readiness audit',
            'Scoped automation or AI workflow pilot',
            'Governance and responsible-use notes',
            'Documentation and user enablement',
        ],
        'tools' => ['n8n', 'Zapier', 'ChatGPT', 'Claude', 'Gemini', 'NotebookLM', 'GPTZero'],
        'timeline' => 'Pilot or advisory',
        'proof_label' => 'See AI credentials',
        'proof_url' => '/certifications',
    ],
    [
        'key' => 'network-consulting',
        'number' => '06',
        'title' => 'Network & Infrastructure Consulting',
        'summary' => 'Practical network assessment, MikroTik and Cisco configuration, troubleshooting, and production support focused on reliability and clear handover.',
        'best_for' => 'Offices, schools, clinics, and growing teams dealing with unstable connectivity, unclear network design, or deployment issues.',
        'deliverables' => [
            'Remote or on-site network assessment',
            'Routing, switching, and wireless design',
            'RouterOS configuration and troubleshooting',
            'Network diagram and configuration handover',
        ],
        'tools' => ['MikroTik', 'RouterOS', 'Cisco', 'Omada', 'DNS', 'SSL', 'cPanel'],
        'timeline' => 'Remote or on-site',
        'proof_label' => 'See network credentials',
        'proof_url' => '/badges',
    ],
    [
        'key' => 'digital-publications',
        'number' => '07',
        'title' => 'Digital Publications & Visual Communication',
        'summary' => 'Editorially structured reports, e-books, magazines, presentations, and campaign assets that communicate with clarity and consistency.',
        'best_for' => 'Teams preparing a publication, report, course, campaign kit, presentation, or reusable visual content system.',
        'deliverables' => [
            'Visual direction and reusable templates',
            'Publication, report, or presentation layout',
            'Campaign and social media asset set',
            'Editable source files and usage guide',
        ],
        'tools' => ['Adobe Creative Suite', 'Canva', 'Microsoft Office', 'Google Workspace'],
        'timeline' => 'Project-based',
        'proof_label' => 'See design archive',
        'proof_url' => '/designs',
    ],
    [
        'key' => 'digital-operations',
        'number' => '08',
        'title' => 'Digital Marketing, CRM & E-commerce Support',
        'summary' => 'Practical setup, content operations, and workflow support for customer journeys, online storefronts, campaigns, and lead management.',
        'best_for' => 'Small teams that need reliable hands-on support connecting content, CRM, e-commerce, and recurring digital operations.',
        'deliverables' => [
            'CRM, funnel, or storefront audit',
            'Lead and email workflow setup',
            'Campaign and storefront content support',
            'Reporting, documentation, and handover',
        ],
        'tools' => ['GoHighLevel', 'Shopify', 'Facebook Ads', 'Canva', 'Google Workspace'],
        'timeline' => 'Project or retained support',
        'proof_label' => 'See professional background',
        'proof_url' => '/#background',
    ],
    [
        'key' => 'speaking-training',
        'number' => '09',
        'title' => 'Speaking, Workshops & Technical Training',
        'summary' => 'Customized talks, panels, workshops, and user training that make technical topics practical for schools, government, health, and community audiences.',
        'best_for' => 'Organizations planning an event, capability-building session, panel, keynote, or practical technical workshop.',
        'deliverables' => [
            'Topic and learning-objective alignment',
            'Custom presentation, demo, or activity',
            'Virtual or on-site delivery with Q&A',
            'Participant resources and follow-up notes',
        ],
        'tools' => ['Responsible AI', 'Digital transformation', 'Cybersecurity', 'Data literacy', 'Health IT', 'Networking'],
        'timeline' => 'Single session or series',
        'proof_label' => 'See achievements & credentials',
        'proof_url' => '/#achievements',
    ],
];
